USE [master]
GO
/****** Object:  Database [SMSproject]    Script Date: 6/14/2026 8:32:05 PM ******/
CREATE DATABASE [SMSproject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMSproject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SMSproject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMSproject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\SMSproject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [SMSproject] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMSproject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SMSproject] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SMSproject] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SMSproject] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SMSproject] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SMSproject] SET ARITHABORT OFF 
GO
ALTER DATABASE [SMSproject] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SMSproject] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SMSproject] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SMSproject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SMSproject] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SMSproject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SMSproject] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SMSproject] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SMSproject] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SMSproject] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SMSproject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SMSproject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SMSproject] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SMSproject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SMSproject] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SMSproject] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SMSproject] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SMSproject] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SMSproject] SET  MULTI_USER 
GO
ALTER DATABASE [SMSproject] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SMSproject] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SMSproject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SMSproject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SMSproject] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SMSproject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SMSproject] SET QUERY_STORE = ON
GO
ALTER DATABASE [SMSproject] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
ALTER DATABASE [SMSproject] SET  READ_WRITE 
GO
